#!/bin/bash
#
# iflog - find lines containing search string in Irssi IRC chatlog 

# Copyright (C) 2015  Digidog - Released under GPL v3

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# @TODO - problem: we cant use * in the terminal command since terminal 
# already expands it to a path where we are atm, before we arrive at 
# function, which needs the *. We rather should take another route: 
# 2 possible solutions:
# 1) is to use command parameters named like -c=channel -y=year, or 
# 2) to use another wildcard (*) pseudosymbol (#) which 
# we can change to * in the function, when we build the path.

iflogDIR="$(dirname "$(readlink -f "$0")")"

shopt -s nullglob

function Help(){

cat << EOF

 following arguments are required:
 [search-item] [year] [channel] [month-day] (e.g.: searchword 2015 bash 01-02)
 [!] year channel month-day are optional but must stay in order. You can't add a channel without a year.

EOF
}

case "$1" in
	-h|--help)
		Help
		exit 1
		;;
	-s|--search)
		read -p "search string you want to look for?:" iflogSEARCH
		read -p "year you want to look in particular? (year[4digits]/none):" iflogYEAR
		read -p "channel you want to look in particular? (channel/none):" iflogCHAN
		read -p "month you want to look in particular? (month[2digits]/none):" iflogMONTH
		read -p "day of month you want to look in particular? (day[2digits]/none):" iflogDAY
    grep -rEi "$iflogSEARCH" --color $HOME/.irssi/chat_log/$iflogYEAR/$iflogCHAN/$iflogMONTH-$iflogDAY.log
		;;
		*)
		a=("$@"); for i in {0..3} ; do a[i]=${a[i]-*} ; done
		grep -rEi "${a[0]}" --color $HOME/.irssi/chat_log/${a[1]}/${a[2]}/${a[3]}.log
		;;
esac

shopt -u nullglob

exit 0
